name: simple_file_log
description: "A new Flutter project."
version: 0.0.1
homepage: https://github.com/xxzj990/simple_file_log

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  intl: ^0.19.0
  logging: ^1.2.0
  path: ^1.8.3
  path_provider: ^2.1.1

dev_dependencies:
  lints: ^3.0.0
