name: simple_file_log_example
description: "Demonstrates how to use the simple_log plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  simple_file_log:
    path: ../

dev_dependencies:
  lints: ^3.0.0