name: simple_file_log
description: "A log util with file."
version: 0.0.9
homepage: https://github.com/xxzj990/simple_file_log

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  intl: ^0.20.2
  logging: ^1.2.0
  path: ^1.8.3

dev_dependencies:
  lints: ^3.0.0
