name: simple_file_log_flutter
description: "A new Flutter project."
version: 0.0.3
homepage: https://github.com/xxzj990/simple_file_log

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  simple_file_log: ^0.0.3

dev_dependencies:
  flutter_lints: ^2.0.0